### ISSUE TITLE
Quick mastery

### ISSUE THREAD

**Issue by KA101** [ClosetWater/KRL_Mods#7]
https://github.com/ClosetWater/KRL_Mods/blob/1d5642983f9a1f39628b7d90ee20c94152520947/A36%20High%20Elves/technology.txt#L15C3-L15C3

Seems kinda weird that one can go direct to master alchemy without advanced alchemy.  If that's intended, might be worth renaming the tech "Elven alchemy" or similar.

**Comment by ClosetWater** [comment]
Not intended and has been remedied.
