### ISSUE TITLE
Forging Overpower Mode

### ISSUE THREAD

**Issue by KA101** [ClosetWater/KRL_Mods#8]
I had some levelups available for my troops (not sure why, but OK), so I opted to give my elven blacksmith a forging upgrade.  The tooltip said it'd improve the attribute by 8.  OK.

So after the upgrade, the blacksmith's forging is now precisely 8.  Hmm
BUT WAIT
the Elven forging, which was the 25, is now 405.  I understand that high stats lead to better gear made faster, but legendary crafting in A36 is set at 45-50.  I suspect an errant multiplier somewhere.
![405](https://github.com/ClosetWater/KRL_Mods/assets/4195632/108da54f-4d86-42f8-9dab-9f003aa6bbd6)

(Incidentally, it's probably good form to have faction units have general-competency in the relevant generic skill(s): a smith should have 25-30 or so Vanilla-Forging.  In case someone attacks a retired dungeon that uses your faction, the crafters should be somewhat useful to folks who don't have Elven crafting gear.)

**Comment by ClosetWater** [comment]
## Infinite Elven Forging
In furniture.txt there was a usageType = UsageEffect on the ELVEN_ANVIL that would IncreaseAttr ELVEN_FORGE by 20 for every turn it was used. It was removed and replaced with: 
```
usageType = UsageEffect "forge " Chain {
     Chance 0.9 CreatureMessage { "forge some ore" "forges some ore" }
     Chance 0.3 Filter And { CreatureId "ELVEN_SMITH" } Lasting 3 ELVEN_FORGING
     Chance 0.5 Filter And { CreatureId "ELVEN_LEGEND_SMITH" } Lasting 3 ELVEN_FORGING }
```

**Comment by KA101** [comment]
Objection: the problem with dwarf-style levelup giving vanilla Forge, whilst the crafting looks for Elven Forge, remains.  Would recommend either phasing out the dwarf-style levelup or finding a way to point it at the correct Elven Forge skill.

(And, ideally, making the smiths compatible with non-Elf factions who might capture them.  Currently the system feels like "nyah nyah our crafters aren't worth capturing".)
